### PR TITLE
perl 5.32.0

### PR DESCRIPTION
**Pull request by mrakitin**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mrakitin** [comment]
@conda-forge-admin, please rerender

**Comment by mrakitin** [comment]
I bumped the build number to `1000`. I heard something it will have some effect on compilers.   Or should it be reset to actual `0`?

**Comment by mrakitin** [comment]
Also, regarding the license, the `Copying` file which comes in https://www.cpan.org/src/5.0/perl-5.32.0.tar.gz is GNU-GPL. I guess the license here should be updated.

Regarding the Windows builds, this is the latest one at the moment: http://strawberryperl.com/download/5.30.2.1/strawberry-perl-5.30.2.1-64bit.msi. Worth skipping for now?

**Comment by isuruf** [comment]
@conda-forge/perl, this is ready now

**Comment by isuruf** [comment]
@conda-forge/core, this is ready for review. I'm adding myself as a maintainer.

**Comment by beckermr** [comment]
Do we want to tell the bioconda folks?

**Comment by isuruf** [comment]
cc @conda-forge/bioconda-recipes

**Comment by isuruf** [comment]
ping on this

**Review by chrisburr — APPROVED** [review]

**Comment by mrakitin** [comment]
Thanks @isuruf for taking care of this PR.

**Pull request merged**
