### PR TITLE
update perl to 5.22

### PR DESCRIPTION
**Pull request by rvalieris**

### CODE REVIEW

**Comment by rvalieris** [comment]
hello @jakirkham, I believe everything is correct now, could you review this PR for me ?
also ping @tomkinsc and @bgruening, I guess.

**Comment by bgruening** [comment]
Looks good to me! Thanks a lot @rvalieris!

**Comment by bgruening** [comment]
@jakirkham can you please merge this? Thanks a lot and happy new year!

**Comment by jakirkham** [comment]
Thanks for the upgrade. Happy New Year.

**Pull request merged**
