### PR TITLE
get new perl version into conda-forge

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by johanneskoester** [comment]
@conda-forge-admin, please rerender

**Comment by bgruening** [comment]
Too bad, it could have been so easy :)

**Comment by johanneskoester** [comment]
@mingwandroid could you help us getting this merged? I think it needs a rerender on your branch.

**Comment by mbargull** [comment]
Maybe you'd rather want to PR from https://github.com/AnacondaRecipes/perl-feedstock/tree/cf-sync (which is at 5.26.0 instead of 5.26.2, though).
You could probably ask @msarahan what's the best thing to do.
Otherwise, I guess, you could:
- fork from https://github.com/AnacondaRecipes/perl-feedstock/tree/cf-sync
-  add https://github.com/AnacondaRecipes/perl-feedstock/commit/08aef46792efa954a6695a9411358bc688f810fc
- rerender
- PR

**Pull request closed without merging**
