### PR TITLE
Include perl 5.22.0

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by bgruening** [comment]
@ocefpaf can I get a merge please? :)
Just out of interest if I want to add yet another release, a new branch is needed, correct? Should this branch then names according to the legacy-version?

**Comment by ocefpaf** [comment]
> @ocefpaf can I get a merge please? :)

I would like if @conda-forge/perl could take a look before I use my "sudo" powers to merge it.

> Just out of interest if I want to add yet another release, a new branch is needed, correct? Should this branch then names according to the legacy-version?

Unless you want to keep maintaining them with patches and updates I do not recommend that. I would add the oldest one you want now, in this PR, and then keep updating it until you reach the current version.

**Comment by bgruening** [comment]
> Unless you want to keep maintaining them with patches and updates I do not recommend that. I would add the oldest one you want now, in this PR, and then keep updating it until you reach the current version.

I was just wondering, because I think it is worth to maintain different versions of one package for reproducibility reasons. I don't care much about perl, but conda-forge should maybe have a recommended way to address this besides the git history.

Thanks!

**Comment by ocefpaf** [comment]
> but conda-forge should maybe have a recommended way to address this besides the git history.

I disagree. We need active feedstocks only for active packages. Otherwise the `git` is enough for reproducibility.

**Comment by ocefpaf** [comment]
> @ocefpaf who decides what is active and what is not?

The maintainers.

> Assuming I have an older perl with an ssl bug, I need to get this version out of the git history, patch it, merge it, revert everything to get to a newer version?

If that is a one time thing, yes. If not then the maintainers may create a new branch and keep updating it.

The thing is balancing reproducibility with maintenance burden vs "just move to the newer version."

**Comment by bgruening** [comment]
Ok, this sounds better, so if the maintainer agrees we can have multiple branches :)
I don't really see why multiple branches are a maintenance burden but it's nice to know this is up to the maintainer and conda-forge in general supports it.

Thanks again!

**Comment by ocefpaf** [comment]
> I don't really see why multiple branches are a maintenance burden but it's nice to know this is up to the maintainer and conda-forge in general supports it.

It is because the bots will consider all the branches 'first class citizens' by updating the feedstock, rerendering, linting, etc. That will consume resources and, if the maintainers cannot justify the need for many branches, we may ask to close them.

**Comment by bgruening** [comment]
@jakirkham can we get a merge here? Thanks!

**Comment by bgruening** [comment]
That was fast, thanks!

**Comment by ocefpaf** [comment]
Not really. This PR sat here for a while.

**Pull request merged**
