### PR TITLE
Fix ar

### PR DESCRIPTION
**Pull request by hmaarrfk**
I found this when compiling for aarch64
The AR command wasn't natively provided by my docker image.

https://github.com/Archiconda/perl-feedstock/issues/1

Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mariusvniekerk** [comment]
@conda-forge-admin please rerender

**Comment by mariusvniekerk** [comment]
@conda-forge-admin please rerender

**Comment by mariusvniekerk** [comment]
Adding the migrator pieces to this too

**Comment by mariusvniekerk** [comment]
qemu based builds take about an hour for perl

**Comment by hmaarrfk** [comment]
;) gotta use native :D

**Pull request merged**
